local file = io.open("head.html", "r")
io.input(file)
local t = io.read("*a")
file = io.open("output/index.html", "w")
file:write(t)
file:close()

file = io.open("sections/Home.html", "r")
io.input(file)
t = io.read("*a")
file = io.open("output/index.html", "a")
file:write(t)
file:close()

file = io.open("sections/About.html", "r")
io.input(file)
t = io.read("*a")
file = io.open("output/index.html", "a")
file:write(t)
file:close()

file = io.open("foot.html", "r")
io.input(file)
t = io.read("*a")
file = io.open("output/index.html", "a")
file:write(t)
file:close()

